# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: volatile
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: proving-ground-backend
service: proving-ground-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  memorySize: 256 # Enough for simple math
  timeout: 10

package:
  patterns:
    - '!venv/**'          # Ignore the virtual environment (huge!)
    - '!tests/**'         # Ignore tests
    - '!__pycache__/**'   # Ignore python cache
    - '!.git/**'          # Ignore git history
    - '!.gitignore'
    - '!README.md'
    - '!requirements.txt' # The plugins handle this, don't need the text file in lambda

functions:
  api:
    handler: app.main.handler # Points to the Mangum handler
    events:
      - http:
          path: /{proxy+} # Capture ALL paths
          method: any
      - http:
          path: / # Capture root path
          method: any
